Review nits

diff --git a/tools/unlock-device b/tools/unlock-device
--- a/tools/unlock-device
+++ b/tools/unlock-device
@@ -2,16 +2,15 @@
 # -*- Mode: sh; indent-tabs-mode: nil; tab-width: 4 -*-
 
 # Our goal here is to get an Ubuntu Touch device into a testable unlocked state.
-# This will include reboots.
+# This will include a reboot.
 
-boot_delay=20
-max_retries=5
-
-ANDROID_SERIAL=$1
-if [ -z "$ANDROID_SERIAL" ]; then
-    echo "E: Please provide an adb device number as an argument"
-    exit 1
-fi
+while getopts s: opt; do
+        case $opt in
+        s)
+                export ANDROID_SERIAL=$OPTARG
+                ;;
+        esac
+done
 
 UNLOCK_SCRIPT='
 import dbus, logging;
@@ -24,26 +23,15 @@ bus.clearSysState(cookie, dbus_interface="com.canonical.powerd");
 helpers.unlock_unity()
 '
 
-retries=0
-while [ $retries -lt $max_retries ]; do
-    ((retries += 1))
-    adb -s $ANDROID_SERIAL reboot
-    sleep 5
-    adb -s $ANDROID_SERIAL "wait-for-device"
-    sleep $boot_delay
-    UNLOCK_OUTPUT=$(adb -s $ANDROID_SERIAL shell "sudo -u phablet -i python3 -c '$UNLOCK_SCRIPT'" 2>&1)
-    if echo "$UNLOCK_OUTPUT" | grep 'Greeter unlocked' >/dev/null; then
-        echo "I: Unlock passed"
-        retries=$max_retries
-    else
-        echo "I: Unlock script output: '$UNLOCK_OUTPUT'"
-        if [ $retries -lt $max_retries ]; then
-            echo "W: Unlock failed, trying again"
-        else
-            echo "E: Unlock failed, no more retries"
-            exit 1
-        fi
-    fi
-done
-
-exit 0
+adb reboot
+sleep 5
+adb "wait-for-device"
+sleep 20
+UNLOCK_OUTPUT=$(adb shell "sudo -u phablet -i python3 -c '$UNLOCK_SCRIPT'" 2>&1)
+if echo "$UNLOCK_OUTPUT" | grep 'Greeter unlocked' >/dev/null; then
+    echo "I: Unlock passed"
+    exit 0
+else
+    echo "I: Unlock failed, script output: '$UNLOCK_OUTPUT'"
+    exit 1
+fi
